[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
fs_permissions = [{ access = "read-write", path = "./"}]
optimizer = true
optimizer_runs = 10
ignored_error_codes = []

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"

[fuzz]
runs = 50
max_test_rejects = 200000

[profile.cibuild]
via_ir = true

[profile.citest]
via_ir = false
ignored_error_codes = ["license", "code-size"]
[profile.citest.fuzz]
runs = 100
